pipeline:
  - name: Install dependencies
    type: command
    command: composer install --no-interaction --optimize-autoloader
    directory: $APP_ROOT

  - name: Import configurations
    command: drush config-import -y
    directory: $APP_ROOT

  - name: Update database
    command: drush updb -y
    directory: $APP_ROOT

  - name: Run entity updates
    command: drush entity-updates -y
    directory: $APP_ROOT

  - name: Clear cache
    type: command
    command: drush cr
    directory: $APP_ROOT
